#!/usr/bin/env python

numberOfBottles = 9
whatTheyAreBottlesOf = "beer"

while numberOfBottles > 0:

	if numberOfBottles == 1:
		bottleOrBottles="bottle"
	else:
		bottleOrBottles="bottles"


	print("There are", numberOfBottles, bottleOrBottles, "of", whatTheyAreBottlesOf, "on the wall,")
	print(numberOfBottles, bottleOrBottles, "of", whatTheyAreBottlesOf)
	print("If one of those bottles should happen to fall, we'd have")

	numberOfBottles = numberOfBottles - 1

	print(numberOfBottles, bottleOrBottles, "of", whatTheyAreBottlesOf, "on the wall!")

	print("")


print("What a mess -- and a waste of ", whatTheyAreBottlesOf, "!")

